### PR TITLE
Extend integer comparison to support floats / Add additional magic methods to the allowed whitelist

### PR DESCRIPTION
**Pull request by PascalDevenoge**
This change is [Reviewable](https://reviewable.io/reviews/marcoeilers/nagini/182)

### CODE REVIEW

**Comment by PascalDevenoge** [comment]
@marcoeilers There must be some typo somewhere, but I've stared at it for a while and I can't find it.

**Comment by marcoeilers** [comment]
You can add
```
print(resolver.messages())
```
after ``resolved = resolver.run()`` in main.py to get type error messages.
Then I get this: 
```
List(FastMessage(found incompatible type `Int`, expected `Ref`,float.sil@17.35--17.54,true), FastMessage(found incompatible type `Int`, expected `Ref`,float.sil@24.35--24.54,true), FastMessage(found incompatible type `Int`, expected `Ref`,float.sil@31.35--31.54,true), FastMessage(found incompatible type `Int`, expected `Ref`,float.sil@38.35--38.54,true))
```

**Comment by PascalDevenoge** [comment]
@marcoeilers Are circular dependencies in the preamble.index file an issue by any chance?

**Comment by marcoeilers** [comment]
No, I don't think so.

**Comment by PascalDevenoge** [comment]
I think I found the mistake I've made. Some test programs fail to translate after I've adjusted the float type functions, but as far I can see, this only happens to SIF test cases. So I guess I have to make the same changes to the other preamble.index file loaded when enabling SIF mode, is that right?

**Comment by PascalDevenoge** [comment]
@marcoeilers Alright, should be ready now.

**Pull request merged**
